version: "3.3"

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/app/
    ports:
      - 1337:8000
    environment:
      - DEBUG={$DEBUG}
      - SECRET_KEY={$SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS={DJANGO_ALLOWED_HOSTS}
    depends_on:
      - redis
  redis:
    image: redis:alpine
  celery:
    build: ./
    command: celery -A core worker -l info
    volumes:
      - ./project/:/usr/src/app/
    environment:
      - DEBUG={$DEBUG}
      - SECRET_KEY={$SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS={DJANGO_ALLOWED_HOSTS}
    depends_on:
      - redis
  celery-beat:
    build: ./
    command: celery -A core beat -l info
    volumes:
      - ./project/:/usr/src/app/
    environment:
      - DEBUG={$DEBUG}
      - SECRET_KEY={$SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS={DJANGO_ALLOWED_HOSTS}
    depends_on:
      - redis
